### ISSUE TITLE
non deterministic test output in js proxy

### ISSUE THREAD

**Issue by jaeh** [keroserene/snowflake#45]
in my fork:
https://github.com/jaeh/snowflake

i am facing issues running the tests, they randomly fail, output below.
feels like a race condition with some initialisation, but have not yet read through the code enough to understand where.

i had to update the npm packages to get wrtc to build on my machine,
without updates i can neither get node 8, 10, 12 nor 13 to install the packages,
updating also gets rid of all deprecation warnings though, so would be worth it anyways.

can someone with a working clone of the master please test on their machine if the updates i made trigger some bugs there that i am not aware of?

#### steps to reproduce my changes without downloading my fork:
copy following into proxy/package.json, overwriting the existing.
```
  "devDependencies": {
    "eslint": "^6.7.2",
    "jasmine": "^3.5.0"
  },
  "dependencies": {
    "cldr": "^5.5.3",
    "wrtc": "^0.4.2",
    "ws": "^7.2.0",
    "xmlhttprequest": "^1.8.0"
  } 
```
then npm install

edit:
the client seems to work fine.
```
Snowflake: Disabling Snowflake. embed.js:1075:13
Snowflake: == snowflake proxy == embed.js:1082:13
Snowflake: Disabling Snowflake. embed.js:1082:13
Snowflake: Currently not active. embed.js:1082:13
Snowflake: Starting snowflake embed.js:1082:13
Snowflake: Using snowflake:443 as Relay. embed.js:1082:13
Snowflake: Snowflake IDs: ________ embed.js:1082:13
Snowflake: Polling broker.. embed.js:1082:13
```
endedit

test results of five runs, abbreviated:
```
...................................FFF...F..
.............................FFF............
...FFF...F..................................
............................................
.......................FFFF.F...............
```

<details> 
<summary>Full test output of five runs</summary>

#### first run
```
snowflake unit tests
Randomized with seed 89281
Started
...................................FFF...F..

Failures:
1) ProxyPair flushes data between client and relay proxies data from relay to client
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1361:7)
        at <Jasmine>

2) ProxyPair flushes data between client and relay sends nothing with nothing to flush
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1373:7)
        at <Jasmine>

3) ProxyPair flushes data between client and relay proxies data from client to relay
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1349:7)
        at <Jasmine>

4) ProxyPair handles a new data channel correctly
  Message:
    Expected Object({ bufferedAmount: 0, readyState: 'open', send: Function, onopen: Function, onclose: Function, onerror: Function, binaryType: 'arraybuffer', onmessage: Function }) to be null.                                                                                                                                                                                          
  Stack:
    Error: Expected Object({ bufferedAmount: 0, readyState: 'open', send: Function, onopen: Function, onclose: Function, onerror: Function, binaryType: 'arraybuffer', onmessage: Function }) to be null.
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1311:23)
        at <Jasmine>

44 specs, 4 failures
Finished in 0.054 seconds
Randomized with seed 89281 (jasmine --random=true --seed=89281)
npm ERR! Test failed.  See above for more details.
```

#### Full test output of second run

```
> snowflake-pt@0.0.0-git test /snowflake/proxy
> node make.js test

snowflake unit tests
Randomized with seed 94904
Started

.............................FFF............

Failures:
1) ProxyPair flushes data between client and relay proxies data from relay to client
  Message:
    Error: <spyOn> : send() method does not exist
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : send() method does not exist
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1361:7)
        at <Jasmine>

2) ProxyPair flushes data between client and relay sends nothing with nothing to flush
  Message:
    Error: <spyOn> : send() method does not exist
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : send() method does not exist
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1373:7)
        at <Jasmine>

3) ProxyPair flushes data between client and relay proxies data from client to relay
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1349:7)
        at <Jasmine>

44 specs, 3 failures
Finished in 0.049 seconds
Randomized with seed 94904 (jasmine --random=true --seed=94904)
npm ERR! Test failed.  See above for more details.
```

#### Full test output of third run

```
> snowflake-pt@0.0.0-git test /snowflake/proxy
> node make.js test

snowflake unit tests
Randomized with seed 27171
Started

...FFF...F..................................

Failures:
1) ProxyPair flushes data between client and relay sends nothing with nothing to flush
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1373:7)
        at <Jasmine>

2) ProxyPair flushes data between client and relay proxies data from client to relay
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1349:7)
        at <Jasmine>

3) ProxyPair flushes data between client and relay proxies data from relay to client
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1362:7)
        at <Jasmine>

4) ProxyPair handles a new data channel correctly
  Message:
    Expected Object({ bufferedAmount: 0, readyState: 'open', send: Function, onopen: Function, onclose: Function, onerror: Function, binaryType: 'arraybuffer', onmessage: Function }) to be null.                                                                                                                                                                                          
  Stack:
    Error: Expected Object({ bufferedAmount: 0, readyState: 'open', send: Function, onopen: Function, onclose: Function, onerror: Function, binaryType: 'arraybuffer', onmessage: Function }) to be null.
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1311:23)
        at <Jasmine>

44 specs, 4 failures
Finished in 0.048 seconds
Randomized with seed 27171 (jasmine --random=true --seed=27171)
npm ERR! Test failed.  See above for more details.

```
#### Full test output of fourth run

```
j@familiar:/snowflake/proxy$ nt

> snowflake-pt@0.0.0-git test /snowflake/proxy
> node make.js test

snowflake unit tests
Randomized with seed 43902
Started

............................................


44 specs, 0 failures
Finished in 0.057 seconds
Randomized with seed 43902 (jasmine --random=true --seed=43902)
```

#### Full test output of fifth run

```
snowflake unit tests
Randomized with seed 99702
Started

.......................FFFF.F...............

Failures:
1) ProxyPair connects to the relay once datachannel opens
  Message:
    TypeError: Cannot read property 'onopen' of null
  Stack:
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1325:15)
        at <Jasmine>
        at processImmediate (internal/timers.js:439:21)

2) ProxyPair flushes data between client and relay proxies data from relay to client
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1361:7)
        at <Jasmine>

3) ProxyPair flushes data between client and relay sends nothing with nothing to flush
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1373:7)
        at <Jasmine>

4) ProxyPair flushes data between client and relay proxies data from client to relay
  Message:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)                                                                                                                                                      
  Stack:
    Error: <spyOn> : could not find an object to spy upon for send()
    Usage: spyOn(<object>, <methodName>)
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1349:7)
        at <Jasmine>

5) ProxyPair handles a new data channel correctly
  Message:
    Expected Object({ bufferedAmount: 0, readyState: 'open', send: Function, onopen: Function, onclose: Function, onerror: Function, binaryType: 'arraybuffer', onmessage: Function }) to be null.                                                                                                                                                                                          
  Stack:
    Error: Expected Object({ bufferedAmount: 0, readyState: 'open', send: Function, onopen: Function, onclose: Function, onerror: Function, binaryType: 'arraybuffer', onmessage: Function }) to be null.
        at <Jasmine>
        at UserContext.<anonymous> (/snowflake/proxy/test/bundle.spec.js:1311:23)
        at <Jasmine>

44 specs, 5 failures
Finished in 0.064 seconds
Randomized with seed 99702 (jasmine --random=true --seed=99702)
npm ERR! Test failed.  See above for more details.
```
</details>

**Comment by uumaro** [comment]
I tried to reproduce this but could not. I applied your suggested changes to package.json and ran `npm install`.
```diff
--- a/proxy/package.json
+++ b/proxy/package.json
@@ -23,13 +23,13 @@
   "author": "Serene Han",
   "license": "BSD-3-Clause",
   "devDependencies": {
-    "eslint": "^6.0.1",
-    "jasmine": "2.5.2"
+    "eslint": "^6.7.2",
+    "jasmine": "^3.5.0"
   },
   "dependencies": {
-    "cldr": "^5.4.1",
-    "wrtc": "^0.0.61",
-    "ws": "^3.3.1",
+    "cldr": "^5.5.3",
+    "wrtc": "^0.4.2",
+    "ws": "^7.2.0",
     "xmlhttprequest": "^1.8.0"
   }
 }
```

I ran `npm run test` three times and each time got `44 specs, 0 failures`. It also worked fine for me using the original package.json version numbers.

My npm is [version 5.8.0+ds6-4](https://packages.debian.org/buster/npm) from Debian buster and my Node.js is [version 10.15.2~dfsg-2](https://packages.debian.org/buster/nodejs) also from Debian buster. It does emit a warning I don't understand every time I run it, but so far it hasn't caused any problems that I can see. (But I'm inexperienced with npm stuff, you probably know better than I do.) I also haven't seen any deprecation warnings.
```
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
```

I would suggest bisecting the version numbers of the dependencies to try and find a version that (1) works with your Node.js installation, and (2) passes the tests consistently, if such a version exists. Then we may be able to track down what the difference is.

**Comment by jaeh** [comment]
will have a look at this soon (i hope),
plan on using snowflake as base for one of the example webapps for a project of mine,
so this will come up sometime soon,
i will close here until then though,
since the error seems to not be reproducible.

reminder for myself:
distribution i used: lubuntu 19.04, 
nvm for node versioning, 
npm version was default installed when nvm installing node versions.

still weird, 
i have 100++ node projects on my machine,
lots of them by other authors,
this is the only one where i have issues like that.
